<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>Cedric-Belin.fr</Company>
		<Copyright>© Cédric Belin</Copyright>
		<Description>Parse and format to LCOV your code coverage reports.</Description>
		<Product>LCOV Reports for F#</Product>
		<Version>1.0.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Belin.Lcov.Tests</AssemblyName>
		<BaseOutputPath>obj</BaseOutputPath>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Belin.Lcov</RootNamespace>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" Version="4.*" />
		<ProjectReference Include="../Sources/Lcov.fsproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="AssemblyInfo.fs" />
		<Compile Include="BranchCoverage.Tests.fs" />
		<Compile Include="FunctionCoverage.Tests.fs" />
		<Compile Include="LineCoverage.Tests.fs" />
		<Compile Include="SourceFile.Tests.fs" />
		<Compile Include="Report.Tests.fs" />
	</ItemGroup>
</Project>
